### ISSUE TITLE
Using AWS creds from configure-aws-credentials

### ISSUE THREAD

**Issue by santoraed** [theserverfault/aws-lambda-layer-release-action#6]
I've tried setting the id and key from outputs of configure-aws-credentials step, but get this error: `Error: The security token included in the request is invalid.`

```
- name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              id: creds
              with:
                aws-region: us-east-1
                role-duration-seconds: 1200
                role-to-assume: ${{ vars.AWS_ROLE_ARN }}

- name: Release Lambda Layer
              uses: theserverfault/aws-lambda-layer-release-action@v0.1
              with:
                access_key_id: ${{ steps.creds.outputs.aws-access-key-id }}
                secret_access_key: ${{ steps.creds.outputs.aws-secret-access-key }}
                layer_name: ${{ env.layer_name }}
                archive: ${{ env.working_dir }}/layer/${{ env.layer_name }}.zip
                architectures: '["x86_64"]'
                runtimes: '["nodejs20.x"]'
                s3_bucket: ${{ vars.LAMBDA_BUCKET }}
                functions: '["${{ vars.LAMBDA_FUNCTION }}"]'
```
